title: Home page of Charles Finn
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1875
  brandStrength: 0.5033727
  lightness: 0.1875
  brandColors:
    - '#fbfcff'
    - '#000000'
    - '#9d693b'
    - '#412317'
    - '#de995c'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: charlesfinn
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6899642
layout_spectrum: 0.2833052
