name: charlesfinn
favicon: null
layout_spectrum: 0.9110437433701009
typography_spectrum: 0.6603960026986897
title: Home page of Charles Finn
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfcff'
    - '#000000'
    - '#9d693b'
    - '#412317'
    - '#de995c'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
