name: charlesfinn
favicon: null
layout_spectrum: 0.49867
typography_spectrum: 0.26044
title: Home page of Charles Finn
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfcff'
    - '#000000'
    - '#9d693b'
    - '#412317'
    - '#de995c'
  brandStrength: 0.5033727
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
